spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/container_mon
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        order_updates: true
        default_schema: container
    show-sql: true
    open-in-view: false

discord:
  webhook:
    url: https://discord.com/api/webhooks/1370723679108989028/56veh7dFQBqqNMrWXs9-5gr87Ju6i_QcvAbUBwZ5zA1Ps76oF65_uNcXWjS2VvPUHL9r
    connect-timeout: 3

http:
  client:
    connect-timeout: 5